name: HetimaDelphinium
description: A sample Chrome packaged application
dependencies:
  chrome: any
  crypto: any
  dart_web_toolkit: any
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore
  hetimanet:
    git: https://github.com/kyorohiro/dart_hetimanet
transformers:
- chrome
- $dart2js:
    csp: true
